import type { SiteContent } from "../types";
import { factRail } from "../data/property-facts";
import { en } from "./en";

export const fr: SiteContent = {
  ...en,
  locale: "fr",
  languageName: "Français",
  alternateLocale: "en",
  alternateLanguageName: "English",
  seo: {
    title: "Villa dei Limoni | Une villa ligure privée au-dessus de Camogli",
    description: "Une villa avec vue sur mer au-dessus de Camogli, piscine privée, jardins en terrasses et maison de piscine en option, jusqu’à 16 voyageurs.",
    socialTitle: "Villa dei Limoni — Camogli, Ligurie",
    socialDescription: "Une villa privée avec vue sur mer au-dessus de Camogli, jardin en terrasses, piscine et sentiers du parc de Portofino à proximité.",
  },
  navigation: {
    menuLabel: "Menu",
    closeLabel: "Fermer le menu",
    skipLabel: "Aller au contenu",
    bookLabel: "Voir les disponibilités",
    languageLabel: "Changer de langue",
    items: [
      { id: "experience", label: "La maison", href: "#experience" },
      { id: "stays", label: "Séjours", href: "#stays" },
      { id: "gallery", label: "Galerie", href: "#gallery" },
      { id: "layout", label: "Agencement", href: "#layout" },
      { id: "camogli", label: "Camogli", href: "#camogli" },
      { id: "faq", label: "À savoir", href: "#faq" },
    ],
  },
  platforms: en.platforms.map((platform) => ({
    ...platform,
    shortCta: `Voir sur ${platform.name}`,
    availabilityCta: `Voir les disponibilités sur ${platform.name}`,
    externalLabel: `Ouvre l’annonce officielle de Villa dei Limoni sur ${platform.name} dans un nouvel onglet`,
  })),
  hero: {
    eyebrow: "Camogli · Ligurie",
    title: "Une villa ligure privée au-dessus de Camogli.",
    description: "Vue sur mer, jardin en terrasses, piscine privée et Camogli à environ cinq minutes en voiture ou en bus.",
    exploreLabel: "Découvrir la villa",
    scrollLabel: "Faire défiler pour découvrir",
    imageAlt: "Villa dei Limoni et son jardin dominant les eaux bleues du Golfo Paradiso",
  },
  facts: factRail.fr,
  story: {
    eyebrow: "L’expérience",
    title: "Une villa sur trois niveaux dans un jardin ligure en terrasses.",
    lead: "Villa dei Limoni se trouve dans un jardin d’arbres fruitiers et de plantes fleuries au-dessus de Camogli, face au Golfo Paradiso.",
    paragraphs: [
      "La villa principale s’étend sur trois niveaux, avec les pièces de vie au rez-de-chaussée et six chambres climatisées aux deux étages.",
      "À l’extérieur, une piscine de 40 m² avec vue sur mer, un espace repas, un barbecue et un four à bois.",
      "Une maison de piscine indépendante, rénovée en 2024, peut accueillir quatre voyageurs supplémentaires et n’est proposée qu’avec la villa.",
    ],
    imageAlt: "Terrasse en pierre baignée de soleil, entourée d’agrumes et de plantes fleuries",
  },
  stays: {
    eyebrow: "Séjours",
    title: "Une villa, deux configurations.",
    intro: "Choisissez la villa de six chambres pour 12 voyageurs maximum, ou ajoutez la maison de piscine indépendante pour un groupe de 16. Elle n’est proposée qu’avec la maison principale et n’est jamais louée à d’autres voyageurs.",
    comparisonLabels: { guests: "Voyageurs", bedrooms: "Chambres", bathrooms: "Salles de bains", idealFor: "Hébergement" },
    modes: [
      {
        id: "villa", eyebrow: "La maison principale", title: "Villa seule",
        summary: "Trois niveaux pour vivre et dormir, ouverts sur le jardin en terrasses et la mer.",
        capacity: "Jusqu’à 12", bedrooms: "6", bathrooms: "4 complètes + 1 cabinet de toilette", idealFor: "La maison principale sur trois niveaux",
        features: ["Climatisation dans chaque chambre", "Cuisine équipée, salon et salle à manger", "Wi-Fi rapide mesuré à 82 Mbit/s", "Piscine privée, jardin, repas en plein air et deux garages"],
        note: "Le tarif affiché jusqu’à 12 voyageurs couvre uniquement la villa principale.",
      },
      {
        id: "villa-cottage", eyebrow: "La propriété complète", title: "Villa + maison de piscine",
        summary: "La villa principale et une maison privée au bord de la piscine, entièrement rénovée en 2024.",
        capacity: "Jusqu’à 16", bedrooms: "7", bathrooms: "6 complètes + 1 cabinet de toilette", idealFor: "La maison principale et la maison de piscine séparée",
        features: ["Chambre double avec petite salle de bains attenante", "Salon avec canapé-lit double et seconde salle de bains", "Cuisine privée et climatisation", "Vue sur la piscine et le Golfo Paradiso"],
        note: "La maison de piscine est une option et ne peut pas être louée séparément.",
      },
    ],
  },
  gallery: {
    eyebrow: "La maison en images", title: "Entre jardin et mer.",
    intro: "Une sélection des espaces, détails et vues qui donnent son caractère à Villa dei Limoni.",
    allLabel: "Toutes les photos", openLabel: "Ouvrir la photo", closeLabel: "Fermer la galerie", previousLabel: "Photo précédente", nextLabel: "Photo suivante", counterLabel: "Photo",
    chapters: [
      { id: "views", label: "Vues", description: "Vues sur le Golfo Paradiso" },
      { id: "pool-garden", label: "Piscine et jardin", description: "Terrasses, fleurs et eau au-dessus de la mer" },
      { id: "outdoor-dining", label: "Repas en plein air", description: "Espace repas, barbecue et four à bois" },
      { id: "living", label: "Pièces de vie", description: "Salon, salle à manger et cuisine équipée" },
      { id: "bedrooms", label: "Chambres", description: "Six chambres climatisées dans la villa" },
      { id: "bathrooms", label: "Salles de bains", description: "Quatre salles d’eau et un WC au rez-de-chaussée" },
      { id: "cottage", label: "Maison de piscine", description: "Chambre, salon, deux salles de bains et cuisine" },
      { id: "arrival", label: "Arrivée", description: "Environ 70 mètres de chemin piéton en pierre" },
      { id: "camogli", label: "Autour de Camogli", description: "Village, plage, port et sentiers voisins" },
    ],
  },
  layout: {
    eyebrow: "Intérieurs et agencement", title: "De l’espace pour se retrouver. Et pour s’isoler.",
    intro: "La villa principale se déploie sur trois niveaux, séparant les pièces de vie des deux étages de chambres. La maison de piscine offre un espace indépendant au niveau du bassin.",
    goodForLabel: "Configurations proposées", goodFor: "La villa principale accueille jusqu’à 12 voyageurs ; avec la maison de piscine, la capacité atteint 16.", optionalLabel: "En option avec la villa",
    floors: [
      { id: "ground", name: "Niveau jardin", kicker: "Vivre ensemble", summary: "Salon, salle à manger séparée, cuisine équipée et WC.", rooms: [{ room: "Salon", detail: "Espace de vie commun" }, { room: "Salle à manger", detail: "Salle à manger intérieure séparée" }, { room: "Cuisine", detail: "Cuisine équipée" }, { room: "WC", detail: "Toilettes et lavabo" }] },
      { id: "first", name: "Premier étage", kicker: "Trois chambres", summary: "Un étage modulable pour adultes et enfants, avec deux salles d’eau.", rooms: [{ room: "Chambre double", detail: "Un lit double" }, { room: "Chambre avec lits superposés", detail: "Deux couchages superposés" }, { room: "Chambre modulable", detail: "Lit simple transformable en double" }, { room: "Deux salles de bains", detail: "Toutes deux avec douche" }] },
      { id: "second", name: "Deuxième étage", kicker: "Trois chambres", summary: "L’étage supérieur réunit chambres double, à deux lits et avec lits superposés.", rooms: [{ room: "Chambre double", detail: "Un lit double" }, { room: "Chambre à deux lits", detail: "Deux lits simples" }, { room: "Chambre avec lits superposés", detail: "Deux couchages superposés" }, { room: "Deux salles de bains", detail: "Toutes deux avec douche" }] },
      { id: "cottage", name: "Maison de piscine", kicker: "Jusqu’à quatre voyageurs supplémentaires", summary: "Une maison indépendante entièrement rénovée au bord de la piscine, face au golfe.", optional: true, rooms: [{ room: "Chambre double", detail: "Avec petite salle de bains attenante" }, { room: "Salon", detail: "Avec canapé-lit double" }, { room: "Seconde salle de bains", detail: "Pour les voyageurs dormant dans le salon" }, { room: "Cuisine", detail: "Hébergement indépendant et climatisé" }] },
    ],
  },
  outdoors: {
    eyebrow: "La vie dehors", title: "Un jardin ligure en terrasses face à la mer.",
    lead: "Un vaste jardin en terrasses, planté d’arbres fruitiers et de fleurs, soutenu par des murs traditionnels en pierre sèche.",
    quote: "Piscine de 40 m². Repas en plein air. Barbecue et four à bois.",
    features: [
      { title: "Piscine avec vue mer", description: "Une piscine privée de 40 m² face à la mer, construite en 2021." },
      { title: "La grande table", description: "Un espace repas extérieur dominant le jardin, la piscine et le Golfo Paradiso." },
      { title: "Feu et saveurs", description: "Un barbecue et un four à bois sont à disposition dans l’espace extérieur." },
      { title: "Un paysage en terrasses", description: "Arbres fruitiers, plantes fleuries et murs en pierre sèche dessinent le jardin." },
    ],
    imageAlts: ["Piscine privée face à la mer", "Table extérieure au milieu du jardin en terrasses", "Four à bois traditionnel dans le jardin"],
  },
  location: {
    eyebrow: "Camogli et ses environs", title: "Au-dessus de Camogli, près du parc naturel de Portofino.",
    lead: "La villa se trouve dans un quartier calme et verdoyant au-dessus de Camogli, près du parc naturel de Portofino.",
    paragraphs: ["Camogli est à environ cinq minutes en voiture ou en bus, ou 15 à 20 minutes à pied — en descente à l’aller et en montée au retour.", "Santa Margherita, Rapallo, Portofino et Gênes sont accessibles en voiture ; le sentier Camogli–San Rocco–Batterie–San Fruttuoso commence à proximité."],
    details: [{ value: "≈ 5 min", label: "Camogli en voiture ou en bus", description: "Selon la circulation et la saison" }, { value: "≈ 15–20 min", label: "Descente à pied vers Camogli", description: "Le retour est en montée" }, { value: "≈ 80 km", label: "Sentiers balisés", description: "Dans le réseau du parc de Portofino" }],
    highlightsTitle: "Tout près", highlights: ["Plage et port de Camogli", "Sentier Camogli–San Rocco–Batterie–San Fruttuoso", "Parc naturel de Portofino et ses 80 km de sentiers", "Santa Margherita, Rapallo, Portofino et Gênes par la route"],
    privacyNote: "Par respect de la vie privée, ce site indique seulement les hauteurs de Camogli. Les voyageurs confirmés doivent suivre les indications d’arrivée jointes à leur réservation.",
    mapLabel: "Emplacement approximatif sur les hauteurs de Camogli", imageAlt: "Le front de mer coloré et la plage de Camogli vus d’en haut",
  },
  reviews: {
    eyebrow: "Avis des voyageurs", title: "Un lieu dont on se souvient.", intro: "Les avis des annonces officielles citent souvent la vue, le jardin, la piscine, l’agencement pour les groupes et la communication avec l’hôte.",
    platforms: [
      { ...en.reviews.platforms[0], scale: "sur 5", reviewCountLabel: "43 avis voyageurs", verifiedLabel: "Données de l’annonce vérifiées le 3 août 2026", themes: ["Vue", "Piscine", "Espaces extérieurs", "Communication avec l’hôte"] },
      { ...en.reviews.platforms[1], scale: "sur 10", reviewCountLabel: "12 avis voyageurs", verifiedLabel: "Données de l’annonce vérifiées le 3 août 2026", themes: ["Séjours en groupe", "Jardin", "Four en pierre", "Fidèle aux photos"] },
    ],
    proofPoints: ["Une villa et une vue à la hauteur des photos", "Un cadre généreux pour familles et groupes", "La piscine et le jardin au cœur de chaque journée", "Des repas mémorables dehors et une communication attentive"],
    disclaimer: "Les notes et nombres d’avis sont des relevés datés des annonces officielles et peuvent évoluer.",
  },
  booking: {
    eyebrow: "Tarifs et réservation", title: "Organisez une semaine au-dessus de Camogli.", lead: "Disponibilités, prix actualisés, taxes finales et conditions d’annulation sont confirmés sur les annonces officielles Airbnb et Vrbo.",
    rateLabel: "Tarifs", rateValue: "Tarifs hebdomadaires saisonniers disponibles", rateDetail: "Choisissez Villa seule ou Villa + maison de piscine sur la plateforme pour afficher le total de vos dates et de votre groupe.",
    weeklyLabel: "Rythme du séjour", weeklyDetail: "L’annonce Airbnb propose actuellement des séjours de sept nuits à partir du dimanche ; la plateforme confirme la règle selon la saison.",
    taxLabel: "Taxe de séjour", taxDetail: "La taxe de séjour peut s’appliquer selon les règles de la commune de Camogli et est confirmée lors de la réservation.",
    platformNote: "Villa dei Limoni n’accepte aucun paiement sur ce site. Effectuez toute réservation et tout paiement sur Airbnb ou Vrbo.",
  },
  faq: {
    eyebrow: "À savoir", title: "Les informations pratiques, en toute clarté.", intro: "Villa dei Limoni est une propriété à flanc de colline, avec accès piéton, escaliers intérieurs et terrain en terrasses. Ces informations vous aideront à préparer votre séjour.",
    items: [
      { id: "access", question: "Comment rejoindre la villa ?", answer: "Depuis la route carrossable la plus proche, les 70 derniers mètres se parcourent à pied sur une ruelle ligure traditionnelle en pierre, légèrement inclinée. La maison n’est pas accessible directement en voiture." },
      { id: "parking", question: "Un stationnement privé est-il disponible ?", answer: "Oui. Deux garages privés se trouvent à moins de cinq minutes à pied de la villa." },
      { id: "mobility", question: "La propriété convient-elle aux personnes à mobilité réduite ?", answer: "L’accès piéton, les escaliers intérieurs et le jardin en terrasses comportent des pentes et des changements de niveau. Discutez de vos besoins avec la plateforme avant de réserver." },
      { id: "children", question: "Les enfants sont-ils les bienvenus ?", answer: "Oui. Le jardin comprend terrasses, marches, zones surélevées et murs en pierre sèche : la surveillance attentive d’un adulte est indispensable." },
      { id: "pool-season", question: "Quand la piscine est-elle ouverte ?", answer: "La saison de la piscine s’étend de mai à octobre. Confirmez les dates exactes sur la plateforme." },
      { id: "stay-length", question: "Quelle est la durée minimale du séjour ?", answer: "L’annonce Airbnb propose actuellement des séjours de sept nuits avec arrivée le dimanche. Les dates en ligne et la réservation confirmée font foi." },
      { id: "arrival-times", question: "Quels sont les horaires d’arrivée et de départ ?", answer: "L’arrivée commence entre 16 h et 16 h 30 selon la plateforme, et le départ a lieu avant 10 h. Les horaires définitifs figurent dans votre réservation." },
      { id: "pets-events", question: "Les animaux ou les événements sont-ils autorisés ?", answer: "Les animaux et les événements ne sont pas autorisés." },
      { id: "smoking-age", question: "Existe-t-il des restrictions concernant le tabac ou l’âge ?", answer: "Vrbo indique actuellement que fumer est permis uniquement dans les zones désignées et que l’âge minimum du locataire est de 28 ans. Les conditions de la réservation confirmée font foi." },
      { id: "services", question: "La villa offre-t-elle des services hôteliers ?", answer: "Non. Il s’agit d’une location touristique privée, pas d’un hôtel ou d’une chambre d’hôtes. Le ménage supplémentaire, le changement du linge et les consommables ne sont pas fournis pendant le séjour." },
      { id: "tourist-tax", question: "La taxe de séjour est-elle incluse ?", answer: "La taxe de séjour de Camogli peut s’appliquer. Son montant et son mode de perception sont confirmés lors de la réservation." },
      { id: "booking", question: "Pourquoi réserver sur Airbnb ou Vrbo ?", answer: "Ce site présente la villa. Disponibilités, paiements, annulations et assistance restent gérés par la plateforme officielle choisie." },
    ],
  },
  footer: { strapline: "Une villa privée entre jardin et mer.", location: "Camogli · Ligurie · Italie", rights: "Tous droits réservés.", privacyNote: "Les voyageurs confirmés doivent suivre les indications d’arrivée jointes à leur réservation.", backToTopLabel: "Retour en haut" },
};
